name: Test relse
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  pre_release_bin:
    name: Build and Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'

      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Fetch Node Packages
        run: |
          yarn
          echo  ${{ steps.cache.outputs.cache-hit }}

      - name: Build Project
        run: yarn build --prod
        env:
          GULP_PARALLEL: ${{ steps.cache.outputs.cache-hit }}

      - name: Create Archives
        run: yarn cmd archive

      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./packages/bp/archives/botpress*
          prerelease: true
          name: ${{ steps.extract_branch.outputs.branch }}
          tag_name: dev-${{ steps.extract_branch.outputs.branch }}
          target_commitish: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
